sudo: false

language: "java"

jdk: "oraclejdk8"

script: "gradle build"

before_deploy:
  - ./gradlew jar

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: "build/libs/*"
  skip_cleanup: true
  on:
      branch: master